//
//  QueryResult.swift
//  TablePro
//
//  Created by Ngo Quoc Dat on 16/12/25.
//

import Foundation
import TableProPluginKit

struct QueryResult {
    let columns: [String]
    let columnTypes: [ColumnType]
    let rows: [[PluginCellValue]]
    let rowsAffected: Int
    let executionTime: TimeInterval
    let error: DatabaseError?

    /// What the elapsed time was spent on, when the driver could tell. Defaults to the elapsed
    /// number alone so a result built without one reads exactly as it always did.
    var timing: PluginQueryTiming?

    var resolvedTiming: PluginQueryTiming {
        timing ?? PluginQueryTiming(total: executionTime)
    }

    /// Whether the result was truncated due to driver-level row limits
    var isTruncated: Bool = false

    /// Optional status message from the plugin (e.g. server notices, warnings)
    var statusMessage: String?

    var columnMeta: [ResultColumnMeta]?

    /// Per row, what the driver finds that row by again. Only the driver reads it.
    var rowLocators: [String?]?

    /// What the statement printed on the server, read on its own session.
    var serverOutput: PluginServerOutput = .none

    /// Row index to the columns that row has no field for. See `PluginQueryResult.absentCells`.
    var absentCells: [Int: Set<Int>] = [:]

    var isEmpty: Bool {
        rows.isEmpty
    }

    var rowCount: Int {
        rows.count
    }

    var columnCount: Int {
        columns.count
    }

    static let empty = QueryResult(
        columns: [],
        columnTypes: [],
        rows: [],
        rowsAffected: 0,
        executionTime: 0,
        error: nil
    )
}

struct ResultColumnMeta: Sendable {
    let isPrimaryKey: Bool
    let isNullable: Bool
    let isAutoIncrement: Bool
}

/// Database error types
enum DatabaseError: Error, LocalizedError {
    case connectionFailed(String)
    case queryFailed(String)
    case invalidCredentials
    case fileNotFound(String)
    case notConnected
    case unsupportedOperation
    /// One save runs against one database, so a queue that reaches two of them cannot be one
    /// plan. It is refused rather than resolved to whichever database the tab in front happens
    /// to name, which is how a drop queued in one database used to land in another.
    case writeSpansDatabases
    /// The statements are generated by the session's driver before the plan is pinned, so a queue
    /// can only be trusted from the database it was queued in.
    case stagedWriteOutsideBrowsedDatabase(String)
    case statementContainsNulCharacter

    var errorDescription: String? {
        switch self {
        case .connectionFailed(let message):
            return message
        case .queryFailed(let message):
            return message
        case .invalidCredentials:
            return String(localized: "Invalid username or password")
        case .fileNotFound(let path):
            return String(format: String(localized: "Database file not found: %@"), path)
        case .notConnected:
            return String(localized: "Not connected to database")
        case .unsupportedOperation:
            return String(localized: "This operation is not supported")
        case .writeSpansDatabases:
            return String(localized: "Pending changes reach more than one database. Save or discard one database at a time.")
        case .stagedWriteOutsideBrowsedDatabase(let database):
            return String(
                format: String(localized: "Pending table changes belong to %@. Switch to that database to save them, or discard them."),
                database
            )
        case .statementContainsNulCharacter:
            return String(
                localized: "The query contains a NUL character (U+0000) and was not run. Remove it and try again."
            )
        }
    }
}

/// Information about a database table
struct TableInfo: Identifiable, Hashable, Sendable {
    var id: String {
        "\(IdentityPath.qualified(name: name, schema: schema))_\(type.rawValue)"
    }
    let name: String
    let type: TableType
    let rowCount: Int?
    let schema: String?
    let comment: String?

    /// How many partitions this table holds, when the engine reports it with the listing. Nil for
    /// an engine that says nothing, which is not the same as zero: a partitioned table with no
    /// partitions yet answers 0.
    ///
    /// It is not part of the table's identity, because the same table with one more partition is
    /// the same table.
    let partitionCount: Int?

    /// Set for a MariaDB table declared `WITH SYSTEM VERSIONING`.
    ///
    /// A trait rather than a kind, because MariaDB reports `SYSTEM VERSIONED` for a partitioned
    /// table and an unpartitioned one alike, and the object is a plain table for every other
    /// decision: it takes rows, indexes, comments, a rename and a drop. Only TRUNCATE is refused,
    /// measured as ERROR 4137 on 11.4.13.
    ///
    /// Outside `==` and `hash` for the reason `comment` and `partitionCount` are: the same table
    /// with versioning turned on is the same table.
    let isSystemVersioned: Bool

    enum TableType: String, Sendable, CaseIterable {
        case table = "TABLE"
        case view = "VIEW"
        case materializedView = "MATERIALIZED VIEW"
        case foreignTable = "FOREIGN TABLE"
        case systemTable = "SYSTEM TABLE"
        case partitionedTable = "PARTITIONED TABLE"
        case externalTable = "EXTERNAL TABLE"
        case sequence = "SEQUENCE"

        /// Whether a foreign key may point at this object. A view has no rows of its own to
        /// constrain, so a key that names one is a statement the server refuses.
        var isForeignKeyTarget: Bool {
            switch self {
            case .table, .partitionedTable: true
            case .view, .materializedView, .foreignTable, .systemTable, .externalTable, .sequence: false
            }
        }

        /// An external table lives in a catalog outside the database, has no
        /// primary key and no row identifier to target, and rejects UPDATE and
        /// DELETE, so the grid must not offer row editing for one.
        ///
        /// Measured on MariaDB 11.4.13: a sequence takes an INSERT but refuses UPDATE, DELETE and
        /// TRUNCATE with ERROR 1031, so an editable grid over one offers two writes out of three
        /// that the server always refuses.
        var allowsRowEditing: Bool {
            switch self {
            case .view, .materializedView, .externalTable, .sequence:
                return false
            case .table, .foreignTable, .systemTable, .partitionedTable:
                return true
            }
        }

        /// Whether the Backup Dump sheet lists this kind as an object to narrow a dump to.
        ///
        /// Measured: `mysqldump 8.4.11` and `mariadb-dump 12.3.3` write a partitioned table's
        /// `CREATE TABLE ... PARTITION BY` and all of its rows when handed the parent by name, and
        /// `mariadb-dump` writes `CREATE SEQUENCE` plus `DO SETVAL` for a sequence. A view carries
        /// no rows and its definition rides with the schema, which is the gap this does not close.
        var isBackupSelectable: Bool {
            switch self {
            case .table, .partitionedTable, .sequence:
                return true
            case .view, .materializedView, .foreignTable, .systemTable, .externalTable:
                return false
            }
        }

        /// Whether the import sheet may offer this kind as an existing table to insert into.
        ///
        /// Narrower than `isBackupSelectable`: a sequence is worth dumping and is not worth
        /// importing rows into, since MariaDB stores exactly one row in one.
        var acceptsImportedRows: Bool {
            switch self {
            case .table, .partitionedTable:
                return true
            case .view, .materializedView, .foreignTable, .systemTable, .externalTable, .sequence:
                return false
            }
        }
    }

    init(
        name: String,
        type: TableType,
        rowCount: Int?,
        schema: String? = nil,
        comment: String? = nil,
        partitionCount: Int? = nil,
        isSystemVersioned: Bool = false
    ) {
        self.name = name
        self.type = type
        self.rowCount = rowCount
        self.schema = schema
        self.comment = comment
        self.partitionCount = partitionCount
        self.isSystemVersioned = isSystemVersioned
    }

    static func == (lhs: TableInfo, rhs: TableInfo) -> Bool {
        lhs.name == rhs.name && lhs.type == rhs.type && lhs.schema == rhs.schema
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(type)
        hasher.combine(schema)
    }
}

/// Information about a table column
struct ColumnInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let dataType: String
    let isNullable: Bool
    let isPrimaryKey: Bool
    let defaultValue: String?
    let extra: String?
    let charset: String?
    let collation: String?
    let comment: String?
    /// Set when the server allocates the value from a sequence it owns, which it reports separately
    /// from the column default: PostgreSQL leaves `column_default` null for an identity column and
    /// puts the generation in `pg_attribute.attidentity`. Dropping it here made every identity
    /// column look like a column with no default.
    let identityKind: IdentityKind?
    let isGenerated: Bool
    let allowedValues: [String]?
    let generationExpression: String?
    let generationKind: GenerationKind?
    /// The server's own spellings of `dataType`, `defaultValue`, `generationExpression` and
    /// `collation` for a `CREATE TABLE`. `PluginColumnInfo.ddlSpelling` and
    /// `PluginColumnInfo.ddlCollation` say why they differ.
    let ddlSpelling: String?
    let ddlDefault: String?
    let ddlGenerationExpression: String?
    let ddlCollation: String?
    /// The name the column is classified by where `dataType` is the server's declared spelling and
    /// says nothing about what the column holds. `PluginColumnInfo.classificationTypeName` says why.
    let classificationTypeName: String?

    /// What a classifier reads. Every display reads `dataType`, and these differ on PostgreSQL:
    /// `status` is shown and `ENUM` is classified, `posint` is shown and `INTEGER` is classified.
    var typeNameForClassification: String { classificationTypeName ?? dataType }

    init(
        name: String,
        dataType: String,
        isNullable: Bool,
        isPrimaryKey: Bool,
        defaultValue: String? = nil,
        extra: String? = nil,
        charset: String? = nil,
        collation: String? = nil,
        comment: String? = nil,
        identityKind: IdentityKind? = nil,
        isGenerated: Bool = false,
        allowedValues: [String]? = nil,
        generationExpression: String? = nil,
        generationKind: GenerationKind? = nil,
        ddlSpelling: String? = nil,
        ddlDefault: String? = nil,
        ddlGenerationExpression: String? = nil,
        ddlCollation: String? = nil,
        classificationTypeName: String? = nil
    ) {
        self.name = name
        self.dataType = dataType
        self.isNullable = isNullable
        self.isPrimaryKey = isPrimaryKey
        self.defaultValue = defaultValue
        self.extra = extra
        self.charset = charset
        self.collation = collation
        self.comment = comment
        self.identityKind = identityKind
        self.isGenerated = isGenerated
        self.allowedValues = allowedValues
        self.generationExpression = generationExpression
        self.generationKind = generationKind
        self.ddlSpelling = ddlSpelling
        self.ddlDefault = ddlDefault
        self.ddlGenerationExpression = ddlGenerationExpression
        self.ddlCollation = ddlCollation
        self.classificationTypeName = classificationTypeName
    }
}

/// Information about a table-level CHECK constraint.
///
/// `columns` is empty on engines whose catalog cannot answer it (MySQL, MariaDB, SQLite); the
/// grid shows the cell blank there rather than guessing from the expression text.
struct CheckConstraintInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let expression: String
    let columns: [String]
    let isValidated: Bool

    init(name: String, expression: String, columns: [String] = [], isValidated: Bool = true) {
        self.name = name
        self.expression = expression
        self.columns = columns
        self.isValidated = isValidated
    }
}

/// Information about a table index
struct IndexInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let columns: [String]
    let isUnique: Bool
    let isPrimary: Bool
    let type: String  // BTREE, HASH, FULLTEXT, etc.
    let columnPrefixes: [String: Int]?
    let whereClause: String?
    /// The entries of `columns` that are expressions. `PluginIndexInfo.expressions` says why a writer
    /// needs to know.
    let expressions: [String]?
    let includedColumns: [String]?
    /// The server's own spellings for a `CREATE INDEX` on another schema.
    /// `PluginIndexInfo.ddlMethodAndKeys` says why they differ from the fields.
    let ddlMethodAndKeys: String?
    let ddlWhereClause: String?
    let isValid: Bool

    init(
        name: String,
        columns: [String],
        isUnique: Bool,
        isPrimary: Bool,
        type: String,
        columnPrefixes: [String: Int]? = nil,
        whereClause: String? = nil,
        expressions: [String]? = nil,
        includedColumns: [String]? = nil,
        ddlMethodAndKeys: String? = nil,
        ddlWhereClause: String? = nil,
        isValid: Bool = true
    ) {
        self.name = name
        self.columns = columns
        self.isUnique = isUnique
        self.isPrimary = isPrimary
        self.type = type
        self.columnPrefixes = columnPrefixes
        self.whereClause = whereClause
        self.expressions = expressions
        self.includedColumns = includedColumns
        self.ddlMethodAndKeys = ddlMethodAndKeys
        self.ddlWhereClause = ddlWhereClause
        self.isValid = isValid
    }
}

/// Information about a foreign key relationship
struct ForeignKeyInfo: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let column: String
    let referencedTable: String
    let referencedColumn: String
    /// Set only by an engine that names objects in three parts and reports a key pointing outside
    /// the database it was read from. An engine with no schema layer names its referenced database
    /// in `referencedSchema` instead, because that is the column its catalog puts it in.
    let referencedDatabase: String?
    let referencedSchema: String?
    let onDelete: String  // CASCADE, SET NULL, RESTRICT, NO ACTION
    let onUpdate: String
    let isVirtual: Bool

    init(
        name: String,
        column: String,
        referencedTable: String,
        referencedColumn: String,
        referencedDatabase: String? = nil,
        referencedSchema: String? = nil,
        onDelete: String = "NO ACTION",
        onUpdate: String = "NO ACTION",
        isVirtual: Bool = false
    ) {
        self.name = name
        self.column = column
        self.referencedTable = referencedTable
        self.referencedColumn = referencedColumn
        self.referencedDatabase = referencedDatabase
        self.referencedSchema = referencedSchema
        self.onDelete = onDelete
        self.onUpdate = onUpdate
        self.isVirtual = isVirtual
    }
}

struct TriggerInfo: Identifiable, Hashable {
    let name: String
    let timing: String
    let event: String
    let statement: String
    let enabled: Bool?

    /// A trigger name is unique per table on PostgreSQL and Oracle, not per schema, so a
    /// database-wide list keyed on the name alone loses one of any two tables that agree on it.
    let table: String?
    let schema: String?
    let orientation: String?

    /// The runnable CREATE TRIGGER text. `statement` is only the action body.
    let definition: String?
    let attributes: [ObjectAttribute]

    var id: String {
        IdentityPath.joined(
            [schema, table, name].compactMap { $0?.isEmpty == false ? $0 : nil },
            separator: "."
        )
    }

    init(
        name: String,
        timing: String,
        event: String,
        statement: String,
        enabled: Bool? = nil,
        table: String? = nil,
        schema: String? = nil,
        orientation: String? = nil,
        definition: String? = nil,
        attributes: [ObjectAttribute] = []
    ) {
        self.name = name
        self.timing = timing
        self.event = event
        self.statement = statement
        self.enabled = enabled
        self.table = table
        self.schema = schema
        self.orientation = orientation
        self.definition = definition
        self.attributes = attributes
    }

    var qualifiedName: String {
        guard let table, !table.isEmpty else { return name }
        return "\(table).\(name)"
    }
}

/// Connection status
enum ConnectionStatus: Equatable, Sendable {
    case disconnected
    case connecting
    case connected
    case error(String)

    var isConnected: Bool {
        if case .connected = self { return true }
        return false
    }
}
