//
//  QueryExecutionCoordinator+Helpers.swift
//  TablePro
//

import AppKit
import Foundation
import os
import TableProPluginKit
import TableProSQLGrammar

private let helpersLogger = Logger(subsystem: "com.TablePro", category: "QueryExecutionCoordinator")

extension QueryExecutionCoordinator {
    func resolveRowCap(sql: String, tabType: TabType, bypassLimit: Bool = false) -> Int? {
        guard !bypassLimit,
              let cap = QueryExecutor.resolveRowCap(
                  sql: sql, tabType: tabType, databaseType: parent.connection.type
              )
        else {
            return nil
        }
        guard !SQLLimitDetector.hasExplicitRowLimit(
            sql,
            autoLimitStyle: PluginManager.shared.autoLimitStyle(for: parent.connection.type),
            grammar: parent.lexicalGrammar
        ) else {
            return nil
        }
        return cap
    }

    /// The text to send for a tab's read and the cap the app keeps on its result.
    func resolveStatement(sql: String, tabType: TabType, bypassLimit: Bool = false) -> LeadingRowsStatement {
        LeadingRowsStatement.resolve(
            sql,
            rowCap: resolveRowCap(sql: sql, tabType: tabType, bypassLimit: bypassLimit),
            databaseType: parent.connection.type
        )
    }

    func parseSchemaMetadata(_ schema: FetchedTableSchema) -> ParsedSchemaMetadata {
        QueryExecutor.parseSchemaMetadata(
            schema,
            rowMatchExcludedTypePrefixes: PluginManager.shared.rowMatchExcludedTypePrefixes(
                for: parent.connection.type
            ),
            rowMatchTextTypePrefixes: PluginManager.shared.rowMatchTextTypePrefixes(
                for: parent.connection.type
            )
        )
    }

    /// History belongs to the database the tab actually ran on, not to wherever the
    /// sidebar happens to point when the entry is written.
    func historyDatabaseName(tabId: UUID) -> String {
        guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else {
            return parent.browseDatabaseName
        }
        return parent.scope(for: tab)?.database ?? parent.browseDatabaseName
    }

    func historySchemaName(tabId: UUID) -> String? {
        guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else { return nil }
        return parent.scope(for: tab)?.schema
    }

    /// A table tab's SQL is generated by the app for browsing, paging, sorting and filtering.
    /// It is recorded so the user can audit what was sent, but it is not something they authored.
    func historySource(tabId: UUID) -> QueryHistorySource {
        guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else { return .editor }
        return tab.tabType == .table ? .tableBrowse : .editor
    }

    /// Never after the table's definition changed: the keys, defaults, generated columns and row
    /// match policy the tab holds describe the table before the change, and reusing them builds the
    /// next edit against the old definition.
    func isMetadataCached(tabId: UUID, tableName: String) -> Bool {
        guard let idx = parent.tabManager.tabs.firstIndex(where: { $0.id == tabId }),
              !parent.tabSessionRegistry.needsDefinition(tabId)
        else {
            return false
        }
        let tab = parent.tabManager.tabs[idx]
        let tableRows = parent.tabSessionRegistry.tableRows(for: tab.id)
        let enumSetColumnNames: [String] = tableRows.columns.enumerated().compactMap { i, name in
            guard i < tableRows.columnTypes.count,
                  tableRows.columnTypes[i].isEnumType || tableRows.columnTypes[i].isSetType else { return nil }
            return name
        }
        let enumsReady = enumSetColumnNames.allSatisfy { tableRows.columnEnumValues[$0] != nil }
        let cached = tab.tableContext.tableName == tableName
            && !tableRows.columnDefaults.isEmpty
            && !tab.tableContext.primaryKeyColumns.isEmpty
            && tableRows.foreignKeysFetched
            && enumsReady
        helpersLogger.info(
            "[fk] cache check table=\(tableName, privacy: .private(mask: .hash)) defaults=\(tableRows.columnDefaults.count) pks=\(tab.tableContext.primaryKeyColumns.count) fkFetched=\(tableRows.foreignKeysFetched) fks=\(tableRows.columnForeignKeys.count) enumsReady=\(enumsReady) cached=\(cached)"
        )
        return cached
    }

    /// Deliberately does not set `foreignKeysFetched`. The prefetch answers which columns carry the
    /// arrow, which is all the first paint needs; defaults, primary keys, nullability and comments
    /// still come from the table's own metadata fetch, and claiming they had arrived would let
    /// `isMetadataCached` skip it.
    ///
    /// A miss starts the fetch for this scope, so the store refills itself after a schema refresh
    /// or a database switch cleared it. Only this table pays the wait; the next one is answered.
    private func prefetchedForeignKeys(tabIndex: Int, tableName: String) -> [String: ForeignKeyInfo]? {
        guard tabIndex < parent.tabManager.tabs.count,
              let scope = parent.scope(for: parent.tabManager.tabs[tabIndex])
        else { return nil }
        if let cached = SchemaForeignKeyStore.shared.foreignKeysByColumn(for: scope, table: tableName) {
            return cached
        }
        parent.prefetchForeignKeys(scope: scope)
        return nil
    }

    struct ResolvedDisplayMetadata {
        var columnDefaults: [String: String?] = [:]
        var columnForeignKeys: [String: ForeignKeyInfo] = [:]
        var columnEnumValues: [String: [String]] = [:]
        var columnNullable: [String: Bool] = [:]
        var columnComments: [String: String] = [:]
        var columnIdentity: [String: IdentityKind] = [:]
        var generatedColumns: Set<String> = []
        var rowMatchPolicy: RowMatchPolicy = .none
        var hasAuthoritativeSchema = false
        var foreignKeysFetched = false
    }

    /// A rerun answered from cache carries no metadata of its own, so it takes the snapshot the
    /// caller captured when it made that cache decision. That includes the non-writable set, which
    /// `configureForTable` clears on every execution and only a schema fetch refills.
    ///
    /// The snapshot is never re-read from the session here. Reading it at this point reads whichever
    /// result is active by then, and selecting a pinned result while the rerun was in flight made
    /// the rerun adopt that other result's identity and non-writable sets.
    private func resolveDisplayMetadata(
        metadata: ParsedSchemaMetadata?,
        columns: [String],
        columnTypes: [ColumnType],
        tabIndex: Int,
        tableName: String?
    ) -> ResolvedDisplayMetadata {
        var resolved = ResolvedDisplayMetadata()
        for (index, colType) in columnTypes.enumerated() {
            if case .enumType(_, let values) = colType, let vals = values, index < columns.count {
                resolved.columnEnumValues[columns[index]] = vals
            }
        }

        if let metadata {
            resolved.columnDefaults = metadata.columnDefaults
            resolved.columnForeignKeys = metadata.columnForeignKeys ?? [:]
            resolved.columnNullable = metadata.columnNullable
            resolved.columnComments = metadata.columnComments
            resolved.columnIdentity = metadata.columnIdentity
            resolved.generatedColumns = metadata.generatedColumns
            resolved.rowMatchPolicy = metadata.rowMatchPolicy
            resolved.hasAuthoritativeSchema = metadata.isAuthoritative
            resolved.foreignKeysFetched = metadata.columnForeignKeys != nil
            for (col, vals) in metadata.columnEnumValues {
                resolved.columnEnumValues[col] = vals
            }
        }

        if resolved.columnForeignKeys.isEmpty, !resolved.foreignKeysFetched, let tableName {
            resolved.columnForeignKeys = prefetchedForeignKeys(tabIndex: tabIndex, tableName: tableName) ?? [:]
        }

        if let tableName {
            resolved.columnForeignKeys = VirtualForeignKeyMerge.merged(
                real: resolved.columnForeignKeys,
                virtual: virtualForeignKeys(tabIndex: tabIndex, tableName: tableName)
            )
        }
        return resolved
    }

    private func virtualForeignKeys(tabIndex: Int, tableName: String) -> [VirtualForeignKey] {
        guard tabIndex < parent.tabManager.tabs.count,
              let scope = parent.scope(for: parent.tabManager.tabs[tabIndex])
        else { return [] }
        return VirtualForeignKeyStore.shared.virtualForeignKeys(
            for: TableScope(
                connectionId: scope.connectionId,
                database: scope.database,
                schema: scope.schema,
                table: tableName
            )
        )
    }

    private func virtualForeignKeys(tabId: UUID, tableName: String) -> [VirtualForeignKey] {
        guard let idx = parent.tabManager.tabs.firstIndex(where: { $0.id == tabId }) else { return [] }
        return virtualForeignKeys(tabIndex: idx, tableName: tableName)
    }

    /// The keys a committed result is edited by. Keys the tab held for the same table carry over
    /// while its definition is unchanged, until phase 2 reports them. After a definition change they
    /// describe the table as it was, so they are never carried into the new result.
    static func resolvedPrimaryKeys(
        reported: [String]?,
        engineDefault: String?,
        previous: [String],
        definitionChanged: Bool
    ) -> [String] {
        if let reported, !reported.isEmpty {
            return reported
        }
        if let engineDefault {
            return [engineDefault]
        }
        return definitionChanged ? [] : previous
    }

    func applyPhase1Result( // swiftlint:disable:this function_parameter_count
        tabId: UUID,
        columns: [String],
        columnTypes: [ColumnType],
        rows: [[PluginCellValue]],
        executionTime: TimeInterval,
        rowsAffected: Int,
        statusMessage: String?,
        tableName: String?,
        isEditable: Bool,
        metadata: ParsedSchemaMetadata?,
        hasSchema: Bool,
        read: TableFreshness.Read,
        sql: String,
        connection conn: DatabaseConnection,
        isTruncated: Bool = false,
        queryParameterValues: [QueryParameter]? = nil,
        historySQL: String? = nil,
        anchor: StatementAnchor? = nil,
        timing: PluginQueryTiming? = nil,
        viewport: GridReloadIntent = .firstRow,
        serverOutput: PluginServerOutput = .none,
        rowLocators: [String?]? = nil,
        absentCells: [Int: Set<Int>] = [:]
    ) {
        guard let idx = parent.tabManager.tabs.firstIndex(where: { $0.id == tabId }) else { return }

        if let routed = ExplainResultRouter.route(
            sql: sql,
            columns: columns,
            rows: rows,
            databaseType: conn.type,
            declaredVariants: conn.type.explainVariants
        ) {
            applyExplainResult(
                tabId: tabId,
                routed: routed,
                executionTime: executionTime,
                rowCount: rows.count,
                sql: sql,
                historySQL: historySQL ?? sql,
                connection: conn,
                queryParameterValues: queryParameterValues,
                anchor: anchor,
                timing: timing
            )
            return
        }

        let existingTabId = parent.tabManager.tabs[idx].id
        let resolved = resolveDisplayMetadata(
            metadata: metadata,
            columns: columns,
            columnTypes: columnTypes,
            tabIndex: idx,
            tableName: tableName
        )
        let generatedColumns = resolved.generatedColumns

        let newTableRows = TableRows.from(
            queryRows: rows,
            columns: columns,
            columnTypes: columnTypes,
            columnDefaults: resolved.columnDefaults,
            columnForeignKeys: resolved.columnForeignKeys,
            columnEnumValues: resolved.columnEnumValues,
            columnNullable: resolved.columnNullable,
            columnComments: resolved.columnComments,
            columnIdentity: resolved.columnIdentity,
            generatedColumns: generatedColumns,
            rowMatchPolicy: resolved.rowMatchPolicy,
            hasAuthoritativeSchema: resolved.hasAuthoritativeSchema,
            foreignKeysFetched: resolved.foreignKeysFetched,
            rowLocators: rowLocators,
            absentCells: absentCells
        )
        let previousTableName = parent.tabManager.tabs[idx].tableContext.tableName
        let definitionChanged = parent.tabSessionRegistry.needsDefinition(existingTabId)
        parent.flushBufferToActiveResult(tabId: existingTabId, pinnedOnly: true)
        parent.setActiveTableRows(newTableRows, for: existingTabId, viewport: viewport)
        /// A count that started before the change can land after it, while the tab is out of sight,
        /// and put the old total back. Kept, a total above the automatic-count threshold stops the
        /// count this read launches, so paging stays bounded by the table as it was.
        let answeredRowsChange = parent.tabSessionRegistry.recordRead(read, for: existingTabId)

        parent.tabManager.mutate(at: idx) { tab in
            tab.schemaVersion += 1
            tab.execution.executionTime = executionTime
            tab.execution.rowsAffected = rowsAffected
            tab.execution.statusMessage = statusMessage
            tab.execution.lastExecutedAt = Date()
            tab.tableContext.tableName = tableName
            tab.tableContext.isEditable = isEditable
            tab.pagination.isLoading = false

            if answeredRowsChange {
                tab.pagination.retireDerivedRowCount()
            }
            if let metadata, let approxCount = metadata.approximateRowCount, approxCount > 0,
               !tab.filterState.hasAppliedFilters {
                tab.pagination.applyDerivedRowCount(approxCount, isApproximate: true)
            }
            if hasSchema {
                tab.metadataVersion += 1
            }

            let rs = ResultSet(
                label: ResultSet.label(tableName: tableName, anchor: anchor, index: 0),
                tableRows: newTableRows
            )
            rs.statementAnchor = anchor
            rs.executionTime = tab.execution.executionTime
            rs.rowsAffected = tab.execution.rowsAffected
            rs.statusMessage = tab.execution.statusMessage
            rs.isTruncated = isTruncated
            rs.baseQuery = sql
            rs.serverOutput = serverOutput

            tab.display.replaceUnpinnedResults(with: [rs])

            if isTruncated {
                tab.pagination.hasMoreRows = true
                tab.pagination.isLoadingMore = false
            } else {
                tab.pagination.resetLoadMore()
            }
            tab.pagination.setBaseQueryForMore(sql, parameterValues: nil)

            if tab.display.isResultsCollapsed {
                tab.display.isResultsCollapsed = false
            }
        }
        parent.toolbarState.isResultsCollapsed = false

        let resolvedPKs = Self.resolvedPrimaryKeys(
            reported: metadata?.primaryKeyColumns,
            engineDefault: PluginManager.shared.defaultPrimaryKeyColumn(for: conn.type),
            previous: tableName == previousTableName ? parent.tabManager.tabs[idx].tableContext.primaryKeyColumns : [],
            definitionChanged: definitionChanged
        )

        parent.tabManager.mutate(at: idx) { $0.tableContext.primaryKeyColumns = resolvedPKs }
        captureOrigin(
            tabIndex: idx,
            tabId: tabId,
            tableName: tableName,
            primaryKeyColumns: resolvedPKs,
            isEditable: isEditable
        )

        if parent.tabManager.selectedTabId == tabId {
            parent.changeManager.configureForTable(
                tableName: tableName ?? "",
                schemaName: parent.tabManager.tabs[idx].tableContext.schemaName,
                columns: columns,
                primaryKeyColumns: resolvedPKs,
                databaseType: conn.type,
                generatedColumns: generatedColumns,
                rowMatchPolicy: resolved.rowMatchPolicy
            )
        }

        recordHistory(
            QueryHistoryRecordRequest(
                query: historySQL ?? sql,
                connectionId: conn.id,
                databaseName: historyDatabaseName(tabId: tabId),
                databaseType: conn.type,
                schemaName: historySchemaName(tabId: tabId),
                source: historySource(tabId: tabId),
                executionTime: executionTime,
                rowCount: rows.count,
                wasSuccessful: true,
                timing: timing
            )
        )

        if parent.tabManager.selectedTabId == tabId, isEditable, !parent.changeManager.hasChanges {
            parent.changeManager.clearChangesAndUndoHistory()
        }
    }

    private func applyExplainResult(
        tabId: UUID,
        routed: ExplainResultRouter.RoutedPlan,
        executionTime: TimeInterval,
        rowCount: Int,
        sql: String,
        historySQL: String,
        connection conn: DatabaseConnection,
        queryParameterValues: [QueryParameter]?,
        anchor: StatementAnchor? = nil,
        timing: PluginQueryTiming? = nil
    ) {
        let databaseName = historyDatabaseName(tabId: tabId)
        let schemaName = historySchemaName(tabId: tabId)
        let historyId = UUID()
        let captured = QueryPlanCaptureBuilder.make(
            subjectSQL: routed.subjectSQL,
            rawPlan: routed.rawText,
            format: routed.format,
            variantKey: routed.variantKey,
            scope: QueryPlanScope(
                connectionId: conn.id,
                databaseType: conn.type,
                databaseName: databaseName,
                schemaName: schemaName
            ),
            executionTime: executionTime,
            capturedAt: Date(),
            historyId: historyId,
            queryParameters: queryParameterValues
        )
        parent.flushBufferToActiveResult(tabId: tabId, pinnedOnly: true)
        parent.tabManager.mutate(tabId: tabId) { tab in
            tab.execution.executionTime = executionTime
            tab.execution.rowsAffected = 0
            tab.execution.statusMessage = nil
            tab.execution.lastExecutedAt = Date()
            tab.pagination.resetLoadMore()
            tab.display.replaceUnpinnedResults(
                with: [ExplainResultSetFactory.make(
                    rawText: routed.rawText,
                    plan: routed.plan,
                    sql: sql,
                    executionTime: executionTime,
                    anchor: anchor,
                    planContext: captured.context
                )]
            )
            if tab.display.isResultsCollapsed {
                tab.display.isResultsCollapsed = false
            }
        }
        parent.seedBufferFromActiveResult(tabId: tabId)
        parent.toolbarState.isResultsCollapsed = false

        recordHistory(
            QueryHistoryRecordRequest(
                id: historyId,
                query: historySQL,
                connectionId: conn.id,
                databaseName: databaseName,
                databaseType: conn.type,
                schemaName: schemaName,
                source: .explain,
                executionTime: executionTime,
                rowCount: rowCount,
                wasSuccessful: true,
                planCapture: captured.capture,
                timing: timing
            )
        )
    }

    func launchPhase2Work(
        tableName: String,
        tabId: UUID,
        connectionType: DatabaseType,
        schemaTask: Task<FetchedTableSchema, Error>?
    ) {
        let isNonSQL = PluginManager.shared.editorLanguage(for: connectionType) != .sql
        let contentEpoch = parent.tabExecution.contentEpoch(for: tabId)
        let resultSetId = parent.tabManager.tabs.first { $0.id == tabId }?.display.activeResultSetId
        Task(priority: .utility) { [weak self, parent] in
            /// The caller marked the total pending when it committed to this phase. Every way out of
            /// here that does not reach `resolveRowCount` has to take that back, or the tab reports a
            /// count that is never coming and never offers `Count Exactly` again.
            guard let self else {
                parent.releaseCountPending(for: tabId)
                return
            }
            guard !parent.isTearingDown else { return }

            let schema = try? await schemaTask?.value
            if schemaTask != nil, schema == nil {
                helpersLogger.error("[fk] phase2 schema fetch failed or cancelled table=\(tableName, privacy: .private(mask: .hash))")
            }

            await MainActor.run { [weak self] in
                guard let self else {
                    parent.releaseCountPending(for: tabId)
                    return
                }
                if let schema {
                    applySchemaMetadata(schema, tabId: tabId, tableName: tableName, resultSetId: resultSetId)
                }
                /// A retarget or a re-execution that overtook this one owns the tab's state now, and
                /// it raised its own pending mark. Clearing here would release the successor's.
                guard parent.tabExecution.isSameContent(contentEpoch, for: tabId) else { return }
                resolveRowCount(
                    tableName: tableName,
                    tabId: tabId,
                    connectionType: connectionType
                )
            }

            guard !isNonSQL, let schema else { return }

            let columnEnumValues = await parent.fetchEnumValues(
                columnInfo: schema.columns,
                tableName: tableName,
                connectionType: connectionType
            )
            guard !columnEnumValues.isEmpty else { return }

            await MainActor.run { [weak self] in
                guard let self, !Task.isCancelled else { return }
                applyEnumValues(columnEnumValues, tabId: tabId, tableName: tableName, resultSetId: resultSetId)
            }
        }
    }

    /// Stamps the active result with the table its rows came from.
    ///
    /// `QueryTab.tableContext` always describes the newest execution, so a result the user later
    /// clicks back to has to carry its own identity or an edit made on it is written against
    /// whatever ran last (#2243).
    func captureOrigin(
        tabIndex: Int,
        tabId: UUID,
        tableName: String?,
        primaryKeyColumns: [String],
        isEditable: Bool
    ) {
        guard tabIndex < parent.tabManager.tabs.count else { return }
        let context = parent.tabManager.tabs[tabIndex].tableContext
        parent.tabManager.tabs[tabIndex].display.activeResultSet?.origin = ResultOrigin(
            tableName: tableName,
            schemaName: context.schemaName,
            databaseName: historyDatabaseName(tabId: tabId),
            primaryKeyColumns: primaryKeyColumns,
            isEditable: isEditable,
            isView: context.isView,
            objectType: context.objectType,
            keysResolved: true
        )
    }

    /// Phase-2 metadata belongs to the result its fetch was launched for, not to whatever the tab
    /// happens to be showing when it lands. A query tab can hold several results and the user can
    /// switch between them while the schema round trips, so keying on the tab's current table name
    /// paints one table's foreign keys, defaults and primary keys onto another table's rows.
    private func resultStillActive(_ tabId: UUID, _ resultSetId: UUID?) -> Bool {
        parent.tabManager.tabs.contains { $0.id == tabId && $0.display.activeResultSetId == resultSetId }
    }

    private func isActiveTab(_ tabId: UUID) -> Bool {
        guard let activeIdx = parent.tabManager.selectedTabIndex,
              activeIdx < parent.tabManager.tabs.count else { return false }
        return parent.tabManager.tabs[activeIdx].id == tabId
    }

    private func applySchemaMetadata(
        _ schema: FetchedTableSchema,
        tabId: UUID,
        tableName: String,
        resultSetId: UUID?
    ) {
        let parsed = parseSchemaMetadata(schema)
        let mergedForeignKeys = parsed.columnForeignKeys.map { real in
            VirtualForeignKeyMerge.merged(
                real: real,
                virtual: virtualForeignKeys(tabId: tabId, tableName: tableName)
            )
        }
        guard resultStillActive(tabId, resultSetId) else {
            /// The result this was fetched for is still there, the user is just looking at another
            /// one. Dropping the metadata left it with no account of which columns the server owns,
            /// and nothing re-fetches on the way back, so the result stayed that way for good.
            applyPhase2MetadataToInactiveResult(
                parsed: parsed,
                columnForeignKeys: mergedForeignKeys,
                tabId: tabId,
                resultSetId: resultSetId
            )
            helpersLogger.info("[fk] phase2 applied to an inactive result table=\(tableName, privacy: .private(mask: .hash))")
            return
        }
        applyPhase2Metadata(parsed: parsed, columnForeignKeys: mergedForeignKeys, tabId: tabId)
    }

    private func applyPhase2MetadataToInactiveResult(
        parsed: ParsedSchemaMetadata,
        columnForeignKeys: [String: ForeignKeyInfo]?,
        tabId: UUID,
        resultSetId: UUID?
    ) {
        guard let resultSetId,
              let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }),
              let resultSet = tab.display.resultSets.first(where: { $0.id == resultSetId })
        else { return }

        resultSet.tableRows.updateDisplayMetadata(
            columnDefaults: parsed.columnDefaults,
            columnForeignKeys: columnForeignKeys,
            columnNullable: parsed.columnNullable,
            columnComments: parsed.columnComments,
            columnIdentity: parsed.columnIdentity,
            generatedColumns: parsed.generatedColumns,
            rowMatchPolicy: parsed.rowMatchPolicy,
            hasAuthoritativeSchema: parsed.isAuthoritative
        )
        if !parsed.primaryKeyColumns.isEmpty {
            resultSet.origin?.primaryKeyColumns = parsed.primaryKeyColumns
            resultSet.origin?.keysResolved = true
        }
    }

    private func applyEnumValues(
        _ values: [String: [String]],
        tabId: UUID,
        tableName: String,
        resultSetId: UUID?
    ) {
        guard resultStillActive(tabId, resultSetId) else { return }
        let existing = parent.tabSessionRegistry.tableRows(for: tabId)
        let hasNewValues = values.contains { key, value in
            existing.columnEnumValues[key] != value
        }
        guard hasNewValues else { return }

        parent.mutateActiveTableRows(for: tabId) { rows in
            for (col, vals) in values {
                rows.columnEnumValues[col] = vals
            }
            return .columnsReplaced
        }
        parent.tabManager.mutate(tabId: tabId) { $0.metadataVersion += 1 }
        if isActiveTab(tabId) {
            parent.dataTabDelegate?.tableViewCoordinator?.refreshCellPresentations()
        }
    }

    private func applyPhase2Metadata(
        parsed: ParsedSchemaMetadata,
        columnForeignKeys: [String: ForeignKeyInfo]?,
        tabId: UUID
    ) {
        guard parent.tabManager.tabs.contains(where: { $0.id == tabId }) else { return }

        parent.mutateActiveTableRows(for: tabId) { rows in
            rows.updateDisplayMetadata(
                columnDefaults: parsed.columnDefaults,
                columnForeignKeys: columnForeignKeys,
                columnNullable: parsed.columnNullable,
                columnComments: parsed.columnComments,
                columnIdentity: parsed.columnIdentity,
                generatedColumns: parsed.generatedColumns,
                rowMatchPolicy: parsed.rowMatchPolicy,
                hasAuthoritativeSchema: parsed.isAuthoritative
            )
        }

        parent.tabManager.mutate(tabId: tabId) { tab in
            if !parsed.primaryKeyColumns.isEmpty {
                tab.tableContext.primaryKeyColumns = parsed.primaryKeyColumns
                tab.display.activeResultSet?.origin?.primaryKeyColumns = parsed.primaryKeyColumns
                tab.display.activeResultSet?.origin?.keysResolved = true
            }
            if let approxCount = parsed.approximateRowCount, approxCount > 0,
               !tab.filterState.hasAppliedFilters {
                tab.pagination.applyDerivedRowCount(approxCount, isApproximate: true)
            }
            tab.metadataVersion += 1
        }

        if parent.tabManager.selectedTabId == tabId, !parsed.primaryKeyColumns.isEmpty {
            parent.changeManager.setPrimaryKeyColumns(parsed.primaryKeyColumns)
        }

        if parent.tabManager.selectedTabId == tabId {
            parent.changeManager.setGeneratedColumns(parsed.generatedColumns)
            parent.changeManager.setRowMatchPolicy(parsed.rowMatchPolicy)
        }

        let refreshed = isActiveTab(tabId)
        if refreshed {
            parent.dataTabDelegate?.tableViewCoordinator?.refreshCellPresentations()
        }
        helpersLogger.info(
            "[fk] phase2 applied tab=\(tabId, privacy: .public) fks=\(parsed.columnForeignKeys?.count ?? -1) defaults=\(parsed.columnDefaults.count) activeTabRefreshed=\(refreshed)"
        )
    }

    func launchPhase2Count(
        tableName: String,
        tabId: UUID,
        connectionType: DatabaseType
    ) {
        resolveRowCount(
            tableName: tableName,
            tabId: tabId,
            connectionType: connectionType
        )
    }

    /// Validates against the tab's content identity, not the execution claim. The claim is settled
    /// the moment phase 1 is applied, which happens before phase 2 is even dispatched, so a claim
    /// check here is false on every run and the count never lands.
    func resolveRowCount(
        tableName: String,
        tabId: UUID,
        connectionType: DatabaseType
    ) {
        let isNonSQL = PluginManager.shared.editorLanguage(for: connectionType) != .sql
        let countsAutomatically = PluginManager.shared.countsRowsAutomatically(for: connectionType)
        let contentEpoch = parent.tabExecution.contentEpoch(for: tabId)
        let token = UUID()

        parent.tabManager.mutate(tabId: tabId) { $0.pagination.isCountPending = true }

        let task = Task(priority: .utility) { [weak self, parent] in
            guard let self else { return }
            guard !parent.isTearingDown else { return }

            let prepared: (plan: RowCountPlan, count: ExactCountInput?, scope: DatabaseScope?) = await MainActor.run {
                guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else {
                    return (.skip, nil, nil)
                }
                let scope = parent.scope(for: tab)
                let plan = Self.rowCountPlan(
                    isNonSQL: isNonSQL,
                    filterState: tab.filterState,
                    approximateRowCount: tab.pagination.totalRowCount,
                    threshold: AppSettingsManager.shared.dataGrid.countRowsIfEstimateLessThan,
                    countsAutomatically: countsAutomatically
                )
                guard case let .exactCount(filtered) = plan else { return (plan, nil, scope) }
                let queryColumns = parent.queryColumns(for: tab)
                let filters = filtered ? tab.filterState.appliedFilters : []
                let logicMode = tab.filterState.filterLogicMode
                let sql = parent.queryBuilder.buildFilteredCountQuery(
                    tableName: tableName,
                    schemaName: tab.tableContext.schemaName,
                    filters: filters,
                    logicMode: logicMode,
                    columns: queryColumns.columns,
                    columnTypes: queryColumns.columnTypes
                )
                return (plan, ExactCountInput(sql: sql, filters: filters, logicMode: logicMode), scope)
            }

            let outcome = await Self.rowCountOutcome(
                plan: prepared.plan,
                count: prepared.count,
                scope: prepared.scope,
                tableName: tableName
            )

            await MainActor.run {
                /// The flag says a count is running, so it has to clear on every way out, including
                /// the ones that apply nothing. Only the task that still owns the slot may clear it,
                /// or a superseded task would release the successor that replaced it.
                let ownsCount = parent.clearRowCountTask(for: tabId, token: token)
                let isCurrent = parent.tabExecution.isSameContent(contentEpoch, for: tabId)
                parent.tabManager.mutate(tabId: tabId) { tab in
                    if ownsCount {
                        tab.pagination.isCountPending = false
                    }
                    guard isCurrent, let applied = outcome?.appliedTotal else { return }
                    tab.pagination.applyDerivedRowCount(applied.total, isApproximate: applied.isApproximate)
                }
            }
        }
        parent.setRowCountTask(task, token: token, for: tabId)
    }

    /// Runs the plan the caller resolved. Split out so `resolveRowCount` has one exit that clears
    /// `isCountPending`, rather than an early return per plan that leaves it set.
    private static func rowCountOutcome(
        plan: RowCountPlan,
        count exactCount: ExactCountInput?,
        scope: DatabaseScope?,
        tableName: String
    ) async -> RowCountOutcome? {
        guard let scope else { return nil }

        switch plan {
        case .skip:
            return nil
        case .clear:
            return .clear
        case .approximate:
            guard let count = try? await DatabaseManager.shared.withMetadataDriver(scope: scope, { driver in
                try await driver.fetchApproximateRowCount(table: tableName)
            }) else { return nil }
            return .count(count, isApproximate: true)
        case let .filteredNonSQL(filters, logicMode):
            guard let count = try? await DatabaseManager.shared.withMetadataDriver(scope: scope, workload: .bulk, { driver in
                try await driver.fetchFilteredRowCount(table: tableName, filters: filters, logicMode: logicMode)
            }) else { return .clear }
            return .count(count, isApproximate: false)
        case .exactCount:
            guard let exactCount, let sql = exactCount.sql else { return nil }
            do {
                let count = try await DatabaseManager.shared.withMetadataDriver(scope: scope, workload: .bulk) { driver in
                    try await ExactRowCounter.count(
                        on: driver,
                        table: tableName,
                        filters: exactCount.filters,
                        logicMode: exactCount.logicMode,
                        countSQL: sql
                    )
                }
                return count.map { RowCountOutcome.count($0, isApproximate: false) }
            } catch {
                helpersLogger.warning("COUNT query failed for \(tableName): \(error.localizedDescription)")
                return nil
            }
        }
    }

    /// `countsAutomatically` is `PluginManager.countsRowsAutomatically(for:)`: an engine that cannot skip rows, or
    /// whose count is a billed scan, is only counted when the user asks.
    static func rowCountPlan(
        isNonSQL: Bool,
        filterState: TabFilterState,
        approximateRowCount: Int?,
        threshold: Int,
        countsAutomatically: Bool = true
    ) -> RowCountPlan {
        guard countsAutomatically else {
            return filterState.hasAppliedFilters ? .clear : .skip
        }
        if isNonSQL {
            return filterState.hasAppliedFilters
                ? .filteredNonSQL(filters: filterState.appliedFilters, logicMode: filterState.filterLogicMode)
                : .approximate
        }
        let exceedsThreshold = (approximateRowCount ?? 0) >= threshold
        if filterState.hasAppliedFilters {
            return exceedsThreshold ? .clear : .exactCount(filtered: true)
        }
        return exceedsThreshold ? .skip : .exactCount(filtered: false)
    }

    /// Reports a failure that belongs to this tab. Ownership of the window's task handle and the
    /// spinner is settled by the caller before this runs, so nothing here touches them.
    func handleQueryExecutionError(
        _ error: Error,
        sql: String,
        tabId: UUID,
        connection conn: DatabaseConnection,
        serverOutput: PluginServerOutput = .none
    ) {
        let diagnosis = DatabaseWriteRejectionDiagnosis.formatted(error)
        let message = ServerOutputCapture.failureMessage(diagnosis, output: serverOutput)
        helpersLogger.error(
            "Query failed on tab \(tabId, privacy: .public): \(error.publicLogShape, privacy: .public)"
        )
        presentTabFailure(message, announcing: diagnosis, onTab: tabId) { tab in
            tab.execution.errorQuery = sql
            tab.execution.lastExecutedAt = Date()
            tab.execution.executionTime = nil
        }

        recordHistory(
            QueryHistoryRecordRequest(
                query: sql,
                connectionId: conn.id,
                databaseName: historyDatabaseName(tabId: tabId),
                databaseType: conn.type,
                schemaName: historySchemaName(tabId: tabId),
                source: historySource(tabId: tabId),
                executionTime: 0,
                rowCount: -1,
                wasSuccessful: false,
                errorMessage: error.localizedDescription
            )
        )
    }
}

extension QueryExecutionCoordinator {
    /// Shows a failure on the tab it belongs to without recording a statement that never ran, so a
    /// step that fails before the tab's query, such as the database switch in front of it, leaves
    /// no history row and nothing for Fix with AI to rewrite.
    func presentTabFailure(
        _ message: String,
        announcing diagnosis: String,
        onTab tabId: UUID,
        recordingExecution: (inout QueryTab) -> Void = { _ in }
    ) {
        parent.tabManager.mutate(tabId: tabId) { tab in
            tab.execution.errorMessage = message
            tab.pagination.isLoading = false
            recordingExecution(&tab)

            // The banner lives at the top of the results pane, so a collapsed pane hides the only
            // thing telling the user their query failed. Every success path opens it the same way.
            if tab.display.isResultsCollapsed {
                tab.display.isResultsCollapsed = false
            }
        }
        // The toolbar mirrors the selected tab, so a failure on a tab in the background describes
        // itself on its own tab and leaves the window chrome to whatever is actually on screen.
        if parent.tabManager.selectedTabId == tabId {
            parent.toolbarState.isResultsCollapsed = false
            parent.toolbarState.clearQueryTiming(forTab: tabId)
            parent.announceQueryError(diagnosis)
        }
    }
}

internal struct ExactCountInput: Sendable {
    internal let sql: String?
    internal let filters: [TableFilter]
    internal let logicMode: FilterLogicMode
}

enum VirtualForeignKeyMerge {
    /// Virtual keys only supplement columns with no real constraint, so a configured relationship
    /// can never shadow one the catalog reports.
    static func merged(
        real: [String: ForeignKeyInfo],
        virtual virtualKeys: [VirtualForeignKey]
    ) -> [String: ForeignKeyInfo] {
        guard !virtualKeys.isEmpty else { return real }
        let supplements = Dictionary(
            virtualKeys.map { ($0.column, $0.toForeignKeyInfo()) },
            uniquingKeysWith: { first, _ in first }
        )
        return supplements.merging(real) { _, realKey in realKey }
    }
}

enum RowCountPlan: Equatable {
    case skip
    case clear
    case approximate
    case exactCount(filtered: Bool)
    case filteredNonSQL(filters: [TableFilter], logicMode: FilterLogicMode)
}

enum RowCountOutcome: Equatable {
    case count(Int, isApproximate: Bool)
    case clear

    /// An estimate of zero or less means "unknown", never "this table is empty": an un-analyzed
    /// table reports 0 or -1 while holding millions of rows. An exact zero is trustworthy.
    ///
    /// Returns nil for "no answer", which is not the same as an answer of nothing. Phase 1 has
    /// usually already put an estimate on screen by the time this lands, so an unusable estimate
    /// must leave that alone rather than blank it. Only `.clear` means the count is genuinely
    /// gone, which is what a filter change asks for.
    var appliedTotal: (total: Int?, isApproximate: Bool)? {
        switch self {
        case .clear:
            return (nil, false)
        case let .count(value, isApproximate):
            guard value > 0 || (value == 0 && !isApproximate) else { return nil }
            return (value, isApproximate)
        }
    }
}
